/* Iron Tuna — game photographs for the story art. GENERATED by
 * tools/build-action-shots.mjs from tools/nfl-action-shots.json; do not hand-edit.
 * Every file is openly licensed on Wikimedia Commons (CC0, public domain,
 * CC BY or CC BY-SA) and the credit its license requires travels with it:
 * player-search.js prints it under every use. Keys are the player slugs
 * player-search.js indexes. */
window.ITActionShots = {
};
