/* Iron Tuna — the reader's own league, on every page that prints a number.
 *
 * The front page and the insight drops quote points and dollars. Left alone
 * those numbers describe the site's default league (12 teams, $200, full PPR),
 * which is the wrong league for most readers: a $300 budget re-prices every
 * player on the board, and half-PPR or 6-point passing TDs re-orders it.
 * This file is the one place that knows what the reader actually plays, so a
 * story can print THEIR number instead of a stranger's.
 *
 * Two sources, both written by the draft app on this same origin:
 *   iron_tuna_draft_state_v2  — the league itself: teams, budget, format and
 *                               the full custom scoring. The authority.
 *   iron_tuna_values_v1       — a snapshot of the reader's own board: every
 *                               player's value and projected points AT THOSE
 *                               SETTINGS. This is what makes a rank personal;
 *                               without it we can still re-score and re-price,
 *                               we just cannot re-rank.
 *
 * Nothing here invents a league. With no saved settings every accessor that
 * speaks for the reader — has, hasBoard, rankOf, findPlayer — still reports
 * nothing: a reader who has never opened the app must never be shown numbers
 * dressed up as theirs.
 *
 * What they ARE shown is the site's own board (DEFAULT_BOARD_RAW below), at the
 * site's default league, labelled "Default league" and never "Your league".
 * That reader was the one least able to translate "+12% to +18% versus price"
 * on their own, and leaving them a bare percentage was not neutrality — so they
 * get all three readings of it: the dollars, the share of a budget, and the
 * draft slots. tailorLabel() is what keeps the two apart in the copy.
 *
 * It also owns the READING FORMAT — whether a tailored line is written in
 * auction dollars or in snake draft slots. The saved league decides it, auction
 * is the default where nothing is saved, and a page that offers a switch writes
 * the reader's choice back here so it holds on every other page they open.
 *
 * HAND-SYNCED with index.html: SCORING_DEFAULTS mirrors DEFAULT_LEAGUE_CONFIG.
 * scoring, CURVE mirrors LEAGUE_MARKET_CURVE, CURVE_BUDGET mirrors
 * LEAGUE_CURVE_BUDGET, and score() mirrors scoreSkillPlayer/yardageScore/
 * countScore. There is no build step. tools/test-it-league.mjs asserts the
 * copies stay in agreement — change them together.
 */
(function (root) {
  'use strict';

  var DEFAULT_TEAMS = 12, DEFAULT_BUDGET = 200;
  var SCORING_DEFAULTS = {
    passingYardsPerPoint: 25, passingYardsThreshold: 125, passingTD: 4, passingInt: -2, passing2pt: 2,
    rushingYardsPerPoint: 10, rushingYardsThreshold: 0, rushingTD: 6, rushing2pt: 2,
    receivingYardsPerPoint: 10, receivingYardsThreshold: 0, receivingTD: 6, receiving2pt: 2,
    receptionPoints: 1, rbReceptionPoints: 1, fumbleLost: -2, fumble2pt: 2,
    individualFumbleRecoveryTD: 6, individualKickReturnTD: 6, individualPuntReturnTD: 6
  };
  // The client's market curve, and the budget it is drawn at. A league's prices
  // are this curve scaled by (teams x budget) / CURVE_BUDGET — which is the
  // whole of "use the reader's budget": a $300 league pays 1.5x the sheet.
  var CURVE_BUDGET = 1440;
  var CURVE = {
    QB: [25, 20, 17, 14, 11, 10, 7, 5, 4, 4, 3, 3, 2, 2, 1, 1],
    RB: [43, 40, 38, 33, 30, 28, 25, 23, 22, 20, 19, 18, 15, 12, 11, 9, 8, 8, 7, 6, 6, 6, 5, 4, 4, 3, 3, 3, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    WR: [42, 40, 36, 35, 31, 28, 24, 24, 17, 16, 15, 14, 12, 12, 10, 9, 9, 9, 7, 6, 6, 6, 6, 5, 5, 5, 4, 4, 4, 4, 3, 3, 3, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    TE: [32, 28, 20, 14, 11, 9, 7, 6, 5, 5, 3, 2, 2, 2, 1, 1],
    K: [2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    DEF: [3, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  };
  var MIN_BID = 1;
  var FORMAT_WORD = { auction: 'auction', snake: 'snake draft', bestball: 'best ball' };

  // ── the site's own board, for a reader who has not got one ────────────────
  // "name|POS|points" per line, at SCORING_DEFAULTS, generated from the same
  // PROJECTIONS the worker serves. It exists for ONE job: a reader with no
  // saved league still deserves a real number instead of a bare percentage, and
  // the only honest number to give them is the site's own — labelled as the
  // site's own, never as theirs. Points only: with no stat lines it cannot be
  // re-scored at someone else's scoring, which is exactly the promise this file
  // makes everywhere else. Regenerate with tools/build-default-board.mjs.
  // ── generated by tools/build-default-board.mjs — do not hand-edit ──
  var DEFAULT_BOARD_RAW = "Josh Allen|QB|357.5\nJalen Hurts|QB|324.8\nLamar Jackson|QB|320.2\nDrake Maye|QB|316.6\nJayden Daniels|QB|309.2\nJaxson Dart|QB|308.9\nBrock Purdy|QB|308.7\nJoe Burrow|QB|307.4\nBo Nix|QB|306.8\nPatrick Mahomes|QB|300.4\nBaker Mayfield|QB|299.6\nTrevor Lawrence|QB|296.6\nDak Prescott|QB|293.5\nJared Goff|QB|285.4\nCaleb Williams|QB|285.1\nDaniel Jones|QB|284.3\nMatthew Stafford|QB|283.6\nJustin Herbert|QB|278.7\nC.J. Stroud|QB|270.2\nSam Darnold|QB|265.8\nTyler Shough|QB|265.5\nJordan Love|QB|253.5\nJacoby Brissett|QB|252.8\nKyler Murray|QB|249.9\nMalik Willis|QB|246.2\nBryce Young|QB|240.5\nCam Ward|QB|226.4\nAaron Rodgers|QB|220.4\nTua Tagovailoa|QB|219.6\nGeno Smith|QB|200.2\nFernando Mendoza|QB|175.1\nDeshaun Watson|QB|123.8\nShedeur Sanders|QB|81.1\nMichael Penix Jr.|QB|38.5\nKirk Cousins|QB|37.9\nTy Simpson|QB|35.4\nMarcus Mariota|QB|20.4\nDavis Mills|QB|16.5\nTeddy Bridgewater|QB|15.9\nJoshua Dobbs|QB|11.7\nTyson Bagent|QB|11.4\nQuinn Ewers|QB|11.3\nTanner McKee|QB|10.9\nMason Rudolph|QB|10.8\nWill Levis|QB|10.8\nSeth Henigan|QB|9.6\nJoe Milton III|QB|8.7\nAdrian Martinez|QB|8.7\nDesmond Ridder|QB|8.4\nMitch Trubisky|QB|8.3\nWill Howard|QB|8.3\nGarrett Nussmeier|QB|8.2\nTyler Huntley|QB|8.1\nGardner Minshew|QB|8\nShane Buechele|QB|7.8\nJarrett Stidham|QB|7.8\nCarson Beck|QB|5.3\nNick Mullens|QB|4.6\nDrew Allar|QB|4.6\nCole Payton|QB|4.4\nJalen Milroe|QB|1.9\nBehren Morton|QB|1\nCade Klubnik|QB|1\nJahmyr Gibbs|RB|373.2\nChristian McCaffrey|RB|365.2\nBijan Robinson|RB|351.4\nJonathan Taylor|RB|310\nDe'Von Achane|RB|297.9\nJeremiyah Love|RB|282.7\nAshton Jeanty|RB|280.6\nBreece Hall|RB|276.2\nSaquon Barkley|RB|275.5\nKenneth Walker III|RB|273.9\nJosh Jacobs|RB|263.6\nJames Cook|RB|261.2\nDerrick Henry|RB|261.1\nChase Brown|RB|258.9\nJavonte Williams|RB|252.4\nOmarion Hampton|RB|247.7\nCam Skattebo|RB|246.5\nKyren Williams|RB|246.2\nTravis Etienne|RB|228.2\nQuinshon Judkins|RB|227.9\nD'Andre Swift|RB|211.6\nBucky Irving|RB|211.5\nTreVeyon Henderson|RB|211.5\nBhayshul Tuten|RB|207.7\nDavid Montgomery|RB|197.7\nJadarian Price|RB|195.9\nRhamondre Stevenson|RB|193.4\nTony Pollard|RB|192.5\nJ.K. Dobbins|RB|190.8\nKenneth Gainwell|RB|190\nAaron Jones|RB|189.9\nJaylen Warren|RB|187.3\nRico Dowdle|RB|184.5\nChuba Hubbard|RB|182\nRachaad White|RB|173.9\nRJ Harvey|RB|172.7\nKyle Monangai|RB|160.4\nTyrone Tracy Jr.|RB|156.6\nJacory Croskey-Merritt|RB|156.4\nTyjae Spears|RB|155\nBlake Corum|RB|154.8\nIsiah Pacheco|RB|137.9\nJonathon Brooks|RB|137.3\nJordan Mason|RB|133.7\nWoody Marks|RB|129.8\nZach Charbonnet|RB|128.6\nJordan James|RB|125.2\nAlvin Kamara|RB|122.9\nJames Conner|RB|122.5\nDylan Sampson|RB|120\nAdam Randall|RB|119.5\nTy Johnson|RB|117.3\nKaelon Black|RB|115.9\nJustice Hill|RB|113\nChris Rodriguez Jr.|RB|111.9\nBraelon Allen|RB|106.1\nEmari Demercado|RB|104.2\nAJ Dillon|RB|103.7\nSamaje Perine|RB|102.9\nTyler Allgeier|RB|101.7\nChristopher Brooks|RB|100.6\nMalik Davis|RB|94.4\nEmanuel Wilson|RB|94.3\nJawhar Jordan|RB|93.2\nBrian Robinson Jr.|RB|91.7\nKimani Vidal|RB|83\nMike Washington Jr.|RB|79.9\nKendre Miller|RB|76.5\nKeaton Mitchell|RB|72.8\nTank Bigsby|RB|72.2\nKyle Juszczyk|RB|65.2\nJaylen Wright|RB|63.5\nBrashard Smith|RB|54.6\nJerome Ford|RB|49.1\nTy Chandler|RB|45\nDevin Neal|RB|42.6\nIsaac Guerendo|RB|40.3\nElijah Mitchell|RB|39.9\nMichael Burton|RB|34.3\nKaytron Allen|RB|34\nZavier Scott|RB|34\nSean Tucker|RB|32.5\nAustin Ekeler|RB|32.4\nPhil Mafah|RB|32.2\nRoschon Johnson|RB|30.3\nDare Ogunbowale|RB|30.3\nFrank Gore Jr.|RB|28.7\nIsaiah Davis|RB|27.4\nJam Miller|RB|27.4\nSeth McGowan|RB|26.3\nJeremy McNichols|RB|26\nAmeer Abdullah|RB|24.8\nAndrew Beck|RB|19.3\nPuka Nacua|WR|350.6\nJa'Marr Chase|WR|336.6\nJaxon Smith-Njigba|WR|334.8\nAmon-Ra St. Brown|WR|326.5\nCeeDee Lamb|WR|299.9\nJustin Jefferson|WR|289.4\nRashee Rice|WR|281.9\nDrake London|WR|270.5\nGarrett Wilson|WR|263.4\nDeVonta Smith|WR|251.6\nA.J. Brown|WR|247.6\nNico Collins|WR|246.8\nTetairoa McMillan|WR|246.3\nZay Flowers|WR|245.4\nChris Olave|WR|243.1\nGeorge Pickens|WR|240.5\nDavante Adams|WR|234.7\nEmeka Egbuka|WR|232\nTee Higgins|WR|229.5\nJaylen Waddle|WR|223.9\nMalik Nabers|WR|219.4\nLuther Burden III|WR|217.5\nLadd McConkey|WR|214.8\nTerry McLaurin|WR|214.2\nCarnell Tate|WR|212.5\nDJ Moore|WR|209.1\nRome Odunze|WR|208.9\nMarvin Harrison Jr.|WR|207.9\nCourtland Sutton|WR|207.1\nJameson Williams|WR|204.9\nAlec Pierce|WR|199.3\nDK Metcalf|WR|196.4\nMichael Pittman|WR|193.4\nTravis Hunter|WR|193.2\nJordyn Tyson|WR|192.5\nParker Washington|WR|190.3\nMike Evans|WR|188.6\nMatthew Golden|WR|187.5\nMakai Lemon|WR|184.1\nBrian Thomas Jr.|WR|183.7\nKhalil Shakir|WR|181.4\nJakobi Meyers|WR|180.7\nRomeo Doubs|WR|180.7\nQuentin Johnston|WR|179.8\nWan'Dale Robinson|WR|179.4\nChristian Watson|WR|177.2\nXavier Worthy|WR|172.3\nJayden Reed|WR|171.8\nMarvin Mims Jr.|WR|170.1\nKC Concepcion|WR|169.5\nJosh Downs|WR|169.1\nMichael Wilson|WR|168.5\nJordan Addison|WR|166.9\nChris Godwin|WR|159.1\nStefon Diggs|WR|158.9\nCalvin Ridley|WR|156.4\nJayden Higgins|WR|149.7\nJohn Metchie III|WR|149.6\nTheo Wease Jr.|WR|148.9\nJalen Coker|WR|147.1\nTroy Franklin|WR|144.8\nRashid Shaheed|WR|143.8\nJerry Jeudy|WR|140.9\nJalen McMillan|WR|134.4\nDevaughn Vele|WR|134.3\nDenzel Boston|WR|133.3\nTre Tucker|WR|132.2\nTory Horton|WR|130.5\nKayshon Boutte|WR|129.4\nRashod Bateman|WR|125.8\nChimere Dike|WR|124.6\nGermie Bernard|WR|121.1\nAntonio Williams|WR|121\nMarquise Brown|WR|120.7\nAdonai Mitchell|WR|118.6\nElic Ayomanor|WR|116.8\nCooper Kupp|WR|116.1\nJack Bech|WR|115.6\nJa'Kobi Lane|WR|115.2\nJalen Nailor|WR|114.9\nJauan Jennings|WR|114.4\nOmar Cooper Jr.|WR|114.1\nChris Bell|WR|112.3\nTank Dell|WR|110.9\nAshton Dulin|WR|110.3\nAndrei Iosivas|WR|107.2\nMalik Washington|WR|104.8\nDarius Slayton|WR|104.2\nTyquan Thornton|WR|103.3\nCedric Tillman|WR|103.3\nDarnell Mooney|WR|102.7\nOlamide Zaccheaus|WR|101.8\nDemarcus Robinson|WR|100.8\nXavier Hutchinson|WR|99.5\nCalvin Austin III|WR|99.4\nBub Means|WR|99.1\nTed Hurst|WR|97.4\nJahdae Walker|WR|95.8\nKendrick Bourne|WR|94.6\nZachariah Branch|WR|94\nZavion Thomas|WR|93.8\nCaleb Douglas|WR|89.9\nRyan Flournoy|WR|89.4\nJosh Palmer|WR|88.4\nDontayvion Wicks|WR|88.2\nTre' Harris|WR|86.5\nLuke McCaffrey|WR|85.1\nDevontez Walker|WR|84.3\nRoman Wilson|WR|82.4\nKevin Austin Jr.|WR|80.7\nTez Johnson|WR|78.5\nJalen Tolbert|WR|76\nBen Skowronek|WR|71.4\nMack Hollins|WR|70\nSavion Williams|WR|70\nXavier Legette|WR|69.5\nChristian Kirk|WR|67.9\nChris Brazzell II|WR|67.9\nIsaac TeSlaa|WR|65.6\nDe'Zhaun Stribling|WR|54.9\nKeon Coleman|WR|50.7\nBrandon Aiyuk|WR|1.3\nDeebo Samuel|WR|1\nTrey McBride|TE|246.8\nBrock Bowers|TE|242.2\nColston Loveland|TE|207.5\nTyler Warren|TE|204.4\nKyle Pitts|TE|196.9\nSam LaPorta|TE|196.5\nGeorge Kittle|TE|192.3\nHarold Fannin Jr.|TE|183.3\nDallas Goedert|TE|182.8\nMark Andrews|TE|178.8\nTravis Kelce|TE|176.7\nTucker Kraft|TE|175.8\nKenyon Sadiq|TE|167.3\nJake Ferguson|TE|164.3\nCade Otton|TE|160\nT.J. Hockenson|TE|159.1\nIsaiah Likely|TE|158.4\nHunter Henry|TE|150.1\nDalton Kincaid|TE|146.1\nGreg Dulcich|TE|146\nAJ Barner|TE|144.9\nJuwan Johnson|TE|143.9\nBrenton Strange|TE|139.2\nPat Freiermuth|TE|139\nColby Parkinson|TE|131.9\nDalton Schultz|TE|131.3\nGunnar Helm|TE|127.7\nTerrance Ferguson|TE|124.9\nDavid Njoku|TE|123.5\nChigoziem Okonkwo|TE|123.2\nMike Gesicki|TE|123.2\nEvan Engram|TE|122.9\nMason Taylor|TE|122.5\nTyler Higbee|TE|122.4\nOronde Gadsden II|TE|116.2\nTheo Johnson|TE|97.4\nNoah Fant|TE|96.1\nDarnell Washington|TE|91.3\nDawson Knox|TE|88.8\nBrock Wright|TE|88\nCharlie Kolar|TE|87.7\nMarlin Klein|TE|84.5\nMichael Mayer|TE|78.7\nEli Stowers|TE|76.7\nErick All|TE|76.5\nWill Kacmarek|TE|75.7\nTommy Tremble|TE|72.7\nJosh Oliver|TE|72.5\nDavis Allen|TE|71.6\nBen Sims|TE|69.7\nAdam Trautman|TE|68.9\nDaniel Bellinger|TE|67.5\nEli Raridon|TE|64\nJeremy Ruckert|TE|59.2\nCole Kmet|TE|58.9\nAustin Hooper|TE|58.7\nJa'Tavion Sanders|TE|57.6\nLuke Musgrave|TE|55.8\nMatthew Hibner|TE|55.1\nJohn Bates|TE|52.7\nNate Boerkircher|TE|49.6\nGrant Calcaterra|TE|49.4\nNate Adkins|TE|49.2\nElijah Higgins|TE|46";
  // ── end generated ──

  // ── the reading format ────────────────────────────────────────────────────
  // Every tailored line has to commit to a draft type before it can say
  // anything useful: an auction reader wants dollars off their own sheet, a
  // snake reader wants draft slots. The league the app saved answers that by
  // itself — a reader who set up an auction is given auction advice without
  // ever asking, and one who set up a snake gets slots. With no saved league
  // the answer is AUCTION: this is an auction site and its copy is written that
  // way, so an unset reader is never shown draft-slot advice by accident.
  //
  // A reader can disagree with either. The choice a switch writes here outranks
  // the saved league and is remembered across pages, because someone who drafts
  // both ways off one board should not have to re-pick on every visit.
  var READING_KEY = 'iron_tuna_reading_format_v1';
  // Two lenses, not three: best ball IS a draft, so it reads in slots. label()
  // still names the league honestly underneath — "your 12-team best ball".
  function normFormat(f) {
    return f === 'auction' ? 'auction' : (f === 'snake' || f === 'bestball') ? 'snake' : null;
  }
  var readingChoice = null;

  function readJSON(key) {
    try { return JSON.parse(root.localStorage.getItem(key) || 'null'); } catch (e) { return null; }
  }
  function num(v, fallback) { var n = Number(v); return isFinite(n) ? n : fallback; }

  // ── the league ────────────────────────────────────────────────────────────
  var state = readJSON('iron_tuna_draft_state_v2');
  var snap = readJSON('iron_tuna_values_v1');
  if (snap && (!snap.players || !snap.players.length)) snap = null;

  var raw = state && state.config ? state.config : null;
  var cfg = null;
  if (raw || snap) {
    var scoring = {};
    var src = (raw && raw.scoring) || {};
    for (var k in SCORING_DEFAULTS) {
      if (SCORING_DEFAULTS.hasOwnProperty(k)) scoring[k] = num(src[k], SCORING_DEFAULTS[k]);
    }
    // Bonus ladders ride along untouched: they are arrays, and a league that
    // pays a bonus at 100 yards scores differently from one that does not.
    ['passingYardBonuses', 'rushingYardBonuses', 'receivingYardBonuses',
     'receptionBonuses', 'rbReceptionBonuses'].forEach(function (b) {
      scoring[b] = Array.isArray(src[b]) ? src[b] : [];
    });
    cfg = {
      teams: Math.max(2, Math.round(num(raw && raw.teams, num(snap && snap.teams, DEFAULT_TEAMS)))),
      budget: Math.max(1, Math.round(num(raw && raw.budget, num(snap && snap.budget, DEFAULT_BUDGET)))),
      format: (raw && raw.format) || (snap && snap.format) || 'auction',
      scoring: scoring
    };
  }

  // "Custom" is the difference the reader can see. A saved league that matches
  // the site defaults in every respect would re-print the same numbers anyway,
  // so it earns no "your league" labelling — a badge that changes nothing is
  // just noise, and worse, it teaches readers to distrust the ones that matter.
  // Scoring is tracked separately from budget and team count, because a story
  // can honour one without the other: points move with scoring, prices move
  // with the budget.
  var customScoring = false;
  if (cfg) {
    for (var sk in SCORING_DEFAULTS) {
      if (SCORING_DEFAULTS.hasOwnProperty(sk) && cfg.scoring[sk] !== SCORING_DEFAULTS[sk]) customScoring = true;
    }
    ['passingYardBonuses', 'rushingYardBonuses', 'receivingYardBonuses',
     'receptionBonuses', 'rbReceptionBonuses'].forEach(function (b) {
      if (cfg.scoring[b] && cfg.scoring[b].length) customScoring = true;
    });
  }
  var customLeague = !!cfg && (cfg.teams !== DEFAULT_TEAMS || cfg.budget !== DEFAULT_BUDGET);
  var custom = customScoring || customLeague;

  // The lens every tailored line is written through. Reader's own switch first,
  // then the league they saved, then auction. Reading it costs nothing, so a
  // page that offers the switch can ask on every render.
  try { readingChoice = normFormat(root.localStorage.getItem(READING_KEY)); } catch (e) { readingChoice = null; }
  function readingFormat() {
    return readingChoice || (cfg && normFormat(cfg.format)) || 'auction';
  }
  // Returns the format now in force, so a caller can re-render from the answer
  // instead of guessing whether an unrecognised value was taken.
  function setReadingFormat(f) {
    var v = normFormat(f);
    if (!v) return readingFormat();
    readingChoice = v;
    try { root.localStorage.setItem(READING_KEY, v); } catch (e) {}
    return v;
  }
  // True when the saved league itself answers the question — the switch starts
  // on the reader's own format rather than on the site default, and a page can
  // say so instead of implying they picked it.
  function formatFromLeague() { return !readingChoice && !!cfg && !!normFormat(cfg.format); }

  // ── the edition ───────────────────────────────────────────────────────────
  // The reading format above answers one question: dollars or draft slots. The
  // EDITION answers a different one — WHICH OF THE THREE DRAFTS the reader came
  // for. Best ball is its own edition (its own insight pages, its own guides,
  // its own room in the app) even though it reads in slots exactly like a snake
  // draft, so the two cannot share one value: normFormat() folds best ball into
  // snake, and a page that switched on that alone would send a best ball reader
  // to the snake edition of every story.
  //
  // Setting the edition also sets the reading format, so a reader who picks
  // Best Ball on the front page's ribbon is never left reading auction dollars
  // underneath. The reverse is deliberately NOT true: the edition is the
  // coarser choice, and it is the one the reader makes by hand.
  var EDITION_KEY = 'iron_tuna_edition_v1';
  function normEdition(f) {
    return (f === 'auction' || f === 'snake' || f === 'bestball') ? f : null;
  }
  var editionChoice = null;
  try { editionChoice = normEdition(root.localStorage.getItem(EDITION_KEY)); } catch (e) { editionChoice = null; }
  // Same precedence as readingFormat(): the reader's own switch, then the league
  // they saved, then auction — this is an auction site and its copy is written
  // that way, so an unset reader is never dropped into another edition.
  function edition() {
    return editionChoice || (cfg && normEdition(cfg.format)) || 'auction';
  }
  function setEdition(f) {
    var v = normEdition(f);
    if (!v) return edition();
    editionChoice = v;
    try { root.localStorage.setItem(EDITION_KEY, v); } catch (e) {}
    setReadingFormat(v);          // best ball reads in slots; normFormat folds it
    return v;
  }
  // True when nobody has picked and the edition came from the league they saved,
  // so a page can say where it got the answer instead of implying they chose it.
  function editionFromLeague() { return !editionChoice && !!cfg && !!normEdition(cfg.format); }

  // ── scoring: a faithful port of the client's scoreSkillPlayer ─────────────
  function yardageScore(yards, perPoint, threshold, bonuses) {
    if (yards < threshold) return 0;
    // A blanked scoring input saves NaN (parseFloat('')) — a bad divisor here
    // would poison every number this file prints.
    var pts = perPoint > 0 ? yards / perPoint : 0;
    (bonuses || []).forEach(function (b) { if (yards >= b.at) pts += b.points; });
    return pts;
  }
  function countScore(count, perEvent, bonuses) {
    if (!count) return 0;
    var pts = count * perEvent;
    (bonuses || []).forEach(function (b) { if (count >= b.at) pts += b.points; });
    return pts;
  }
  function score(stats, position, scoringOverride) {
    var s = scoringOverride || (cfg && cfg.scoring) || SCORING_DEFAULTS;
    stats = stats || {};
    var pts = 0;
    pts += yardageScore(stats.passYd || 0, s.passingYardsPerPoint, s.passingYardsThreshold, s.passingYardBonuses);
    pts += (stats.passTD || 0) * s.passingTD;
    pts += (stats.passInt || 0) * s.passingInt;
    pts += (stats.pass2pt || 0) * s.passing2pt;
    pts += yardageScore(stats.rushYd || 0, s.rushingYardsPerPoint, s.rushingYardsThreshold, s.rushingYardBonuses);
    pts += (stats.rushTD || 0) * s.rushingTD;
    pts += (stats.rush2pt || 0) * s.rushing2pt;
    pts += yardageScore(stats.recYd || 0, s.receivingYardsPerPoint, s.receivingYardsThreshold, s.receivingYardBonuses);
    pts += (stats.recTD || 0) * s.receivingTD;
    pts += (stats.rec2pt || 0) * s.receiving2pt;
    if (position === 'RB') pts += countScore(stats.rec || 0, s.rbReceptionPoints, s.rbReceptionBonuses);
    else pts += countScore(stats.rec || 0, s.receptionPoints, s.receptionBonuses);
    pts += (stats.fumLost || 0) * s.fumbleLost;
    pts += (stats.fum2pt || 0) * s.fumble2pt;
    pts += (stats.fumRecTD || 0) * s.individualFumbleRecoveryTD;
    pts += (stats.krTD || 0) * s.individualKickReturnTD;
    pts += (stats.prTD || 0) * s.individualPuntReturnTD;
    return pts;
  }

  // Curve slot -> dollars in THIS reader's league. Same shape as the client's
  // calculateMarketValues, so a price quoted in a story is a price they can go
  // and find on their own sheet.
  function price(position, rankIndex) {
    var curve = CURVE[position] || [];
    var scale = (cfg ? cfg.teams * cfg.budget : DEFAULT_TEAMS * DEFAULT_BUDGET) / CURVE_BUDGET;
    var base = rankIndex < curve.length ? curve[rankIndex] : MIN_BID;
    return Math.max(MIN_BID, Math.round(base * scale));
  }

  // A dollar figure written about a MANAGER'S OWN money in the site's default
  // $200 league, restated in the reader's: "how to spend the $200" becomes "how
  // to spend the $300", and a $40 stud in that prose becomes a $60 one.
  //
  // Deliberately scaled by budget alone, not by the league pool. Team count
  // belongs in price(), where more teams means more money chasing the same
  // players; it does not belong here, where the sentence is about one manager's
  // wallet and a 10-team league does not shrink it.
  function money(perTeamDollars) {
    var n = num(perTeamDollars, 0);
    if (!cfg) return Math.round(n);
    return Math.max(0, Math.round(n * cfg.budget / DEFAULT_BUDGET));
  }

  // ── the reader's board ────────────────────────────────────────────────────
  // Suffix first, THEN last word — normName("III") is "", which would bucket
  // every suffixed name under one key. Same rule as my-insights.html.
  function normName(s) {
    return String(s || '').toLowerCase().replace(/\b(jr|sr|ii|iii|iv|v)\.?$/g, '').replace(/[^a-z]/g, '');
  }
  function lastNameKey(s) {
    var w = String(s || '').trim().replace(/\s+(jr|sr|ii|iii|iv|v)\.?$/i, '').split(/\s+/);
    return normName(w[w.length - 1]);
  }
  // One index per pool. Two pools ever exist: the reader's own saved board, and
  // the site's default board below. They are kept strictly apart — `mine` stays
  // null for a reader who has never opened the app, so every accessor that
  // speaks for "their" board still reports nothing rather than quietly
  // answering out of the site's.
  function makeIndex(players) {
    var byName = {}, byLast = {}, byPos = {};
    players.forEach(function (p) {
      byName[normName(p.n)] = p;
      var last = lastNameKey(p.n);
      if (last) (byLast[last] = byLast[last] || []).push(p);
      (byPos[p.pos] = byPos[p.pos] || []).push(p);
    });
    Object.keys(byPos).forEach(function (pos) {
      byPos[pos].sort(function (a, b) { return (b.pts || 0) - (a.pts || 0); });
    });
    return { players: players, byName: byName, byLast: byLast, byPos: byPos };
  }
  var mine = snap ? makeIndex(snap.players) : null;

  // The site's default board, parsed on first use — a reader who has their own
  // never pays for it. Prices come off the market curve at the site's default
  // league, which is the app's own recipe (calculateMarketValues): rank within
  // position by points, read the curve slot, scale by teams x budget.
  var defIndex = null;
  function defaultBoard() {
    if (defIndex) return defIndex;
    var players = [];
    String(DEFAULT_BOARD_RAW).split('\n').forEach(function (line) {
      var f = line.split('|');
      if (f.length === 3 && f[0]) players.push({ n: f[0], pos: f[1], pts: num(f[2], 0) });
    });
    defIndex = makeIndex(players);
    var scale = DEFAULT_TEAMS * DEFAULT_BUDGET / CURVE_BUDGET;
    Object.keys(defIndex.byPos).forEach(function (pos) {
      var curve = CURVE[pos] || [];
      // byPos is already sorted by points, so the array index IS the curve slot.
      defIndex.byPos[pos].forEach(function (p, i) {
        p.v = Math.max(MIN_BID, Math.round((i < curve.length ? curve[i] : MIN_BID) * scale));
      });
    });
    return defIndex;
  }

  // Resolve a name field to a row on a board. The premium insight set stores
  // several names per call, semicolon-separated ("DJ Moore; Allen"), so each
  // entry is tried in order — the first one the board knows wins. A bare surname
  // only resolves when exactly one player at that position carries it; an
  // ambiguous one resolves to nothing rather than to a coin flip.
  // `idx` defaults to the reader's own board, so every existing caller is
  // unchanged; the default-board path passes its own.
  function findPlayer(name, position, idx) {
    var ix = idx || mine;
    if (!ix || !name) return null;
    var entries = String(name).split(';');
    for (var i = 0; i < entries.length; i++) {
      var e = entries[i].trim();
      if (!e) continue;
      var hit = ix.byName[normName(e)];
      if (hit && (!position || position === 'Market' || hit.pos === position)) return hit;
      var cands = (ix.byLast[lastNameKey(e)] || []).filter(function (p) {
        return !position || position === 'Market' || p.pos === position;
      });
      if (cands.length === 1) return cands[0];
    }
    return null;
  }
  // Pull a player the board knows out of a headline. Longest match wins so
  // "Kenneth Walker" is never read as some other Walker, and the search is
  // anchored on word boundaries so "Love" cannot match inside "Loveland".
  function playerInText(text, position, idx) {
    var ix = idx || mine;
    if (!ix || !text) return null;
    var hay = ' ' + String(text).toLowerCase().replace(/[^a-z]+/g, ' ') + ' ';
    var best = null;
    var pool = (position && position !== 'Market' && ix.byPos[position]) ? ix.byPos[position] : ix.players;
    pool.forEach(function (p) {
      var full = ' ' + String(p.n).toLowerCase().replace(/[^a-z]+/g, ' ').trim() + ' ';
      if (full.length > 3 && hay.indexOf(full) >= 0 && (!best || full.length > best.len)) {
        best = { p: p, len: full.length };
      }
    });
    return best ? best.p : null;
  }
  // Where a points total would sit on the reader's board at their scoring. The
  // board is the shipped (odds-blended) one, so this answers "which slot does
  // this land on MY sheet", which is the only rank a reader can act on. Their
  // board only — a reader without one gets null, exactly as before.
  function rankOf(position, pts) {
    var list = mine && mine.byPos[position];
    if (!list || !list.length) return null;
    var n = 1;
    for (var i = 0; i < list.length; i++) if ((list[i].pts || 0) > pts) n++;
    return n;
  }
  // The overall draft order of a board, computed once per board on first use.
  // A DRAFT SLOT is a position in this order, and the order is by VALUE, not by
  // points: an auction dollar means the same thing at every position, and raw
  // fantasy points do not. Ties fall back to points so the order is total.
  function order(ix) {
    if (ix.order) return ix.order;
    ix.order = ix.players.slice().sort(function (a, b) {
      return (b.v || 0) - (a.v || 0) || (b.pts || 0) - (a.pts || 0);
    });
    ix.order.forEach(function (p, i) { p.oi = i; });
    return ix.order;
  }
  // Slots a player moves on a board when their projection shifts by `pct`.
  //
  // Points move a player WITHIN HIS POSITION — that is the only comparison raw
  // fantasy points support. A 300-point QB and a 300-point WR are not adjacent
  // picks, and counting every player of any position sitting between the old and
  // new totals (which this used to do) reported a routine +15% on a WR as a
  // 25-slot move: it was counting quarterbacks he would never be drafted
  // against. So: find the player at his own position he now leapfrogs, and
  // measure the distance to that player on the overall value-ordered board.
  // Returns BOTH the distance and the player leapfrogged: the copy has to know
  // whether the move happened anywhere that matters, and a number alone cannot
  // say. { slots: 0, target: null } when nothing moves.
  function slotMove(p, pct, idx) {
    var ix = idx || mine;
    if (!ix || !p) return { slots: 0, target: null };
    var np = (p.pts || 0) * (1 + pct);
    var list = ix.byPos[p.pos] || [];
    var target = null, i;
    if (pct > 0) {
      // list runs best-first, so the FIRST player he now outscores is the
      // highest slot he reaches; he takes that player's place.
      for (i = 0; i < list.length; i++) {
        if (list[i] === p) break;
        if ((list[i].pts || 0) <= np) { target = list[i]; break; }
      }
    } else {
      // Falling: the LAST player who now outscores him is how far he drops.
      for (i = list.length - 1; i >= 0; i--) {
        if (list[i] === p) break;
        if ((list[i].pts || 0) >= np) { target = list[i]; break; }
      }
    }
    if (!target) return { slots: 0, target: null };
    order(ix);
    return { slots: Math.abs((p.oi || 0) - (target.oi || 0)), target: target };
  }
  // The number on its own, which is all my-insights.html ever wanted.
  function slotsMoved(p, pct, idx) { return slotMove(p, pct, idx).slots; }
  // The endgame tier: players priced at roughly the last 1.5% of a budget, where
  // the board stops being an order at all. Fifty players tie at $1–$2, so the
  // gap between two of them is an artefact of the tie-break, not a draft slot —
  // quoting "63 slots" off it would be precision the number does not have.
  function dartLine(budget) { return Math.max(MIN_BID + 1, Math.round(budget * 0.015)); }
  // How far the move went, as a noun phrase: "6 draft slots (about half a
  // round)", or an honest description where a slot count would be noise.
  // Returns { text, endgame } — endgame true when the phrase describes the tier
  // rather than a distance, because that reads as a different sentence. Empty
  // text means nothing moved.
  //
  // One copy of this: the reader's line and the default-league line print the
  // same phrase, and drifting apart is how two pages start disagreeing about the
  // same call.
  //
  // `scale` restates the two board prices into the same money as `budget`. The
  // site's own board is priced at the desk's league and must stay that way —
  // boardRatio() reads it — so a caller quoting it to a reader on another budget
  // passes leagueScale() here rather than comparing $200 dollars against a $120
  // endgame line, which is how a mid-round back gets called a dart throw.
  function slotPhrase(p, target, a, b, teams, budget, word, scale) {
    if (!target || b === 0) return { text: '', endgame: false };
    var k = scale || 1;
    var pv = Math.max(MIN_BID, Math.round((p.v || 0) * k));
    var tv = Math.max(MIN_BID, Math.round((target.v || 0) * k));
    var dart = dartLine(budget), tier = '$' + MIN_BID + '\u2013$' + dart;
    var lo = Math.min(pv, tv), hi = Math.max(pv, tv);
    if (lo <= dart) {
      return {
        endgame: true,
        text: hi <= dart ? 'a shuffle inside the ' + tier + ' endgame'
            : (pv <= dart ? 'a climb out of ' : 'a slide into ') + tier + ' endgame territory'
      };
    }
    // A range that starts at nothing is not a range: the low end of the
    // editorial percentage simply does not move him, so `b` is a ceiling.
    var count = a === 0 ? b + ' ' + word + 's at most'
              : a === b ? b + ' ' + word + (b === 1 ? '' : 's')
              : a + '\u2013' + b + ' ' + word + 's';
    var rounds = b / teams, r1 = Math.round(rounds * 10) / 10;
    var note = r1 >= 0.9 && r1 <= 1.1 ? ' (about a round)'
             : rounds > 1.1 ? ' (about ' + r1 + ' rounds)'
             : rounds >= 0.45 ? ' (about half a round)' : '';
    return { text: count + note, endgame: false };
  }

  // ── copy helpers ──────────────────────────────────────────────────────────
  // The league in words. `fmtOverride` is the lens the caller is reading
  // through, and when it disagrees with the league the reader actually saved the
  // sentence stops calling it theirs: "worth $4 more in A 10-team, $300 auction"
  // is a true thing to say to a snake-league reader who asked for the auction
  // read — "in YOUR 10-team auction" is not, because they never said that.
  function label(fmtOverride) {
    if (!cfg) return '';
    var f = fmtOverride || cfg.format;
    // Compared through normFormat so best ball read as a snake is still the
    // reader's own league, and still named best ball.
    var mine = normFormat(f) === normFormat(cfg.format);
    var own = mine ? 'your ' : 'a ';
    if (normFormat(f) === 'auction') return own + cfg.teams + '-team, $' + cfg.budget + ' auction';
    return own + cfg.teams + '-team ' + (FORMAT_WORD[mine ? cfg.format : f] || 'league');
  }
  function scoringLabel() {
    if (!cfg) return '';
    var rec = cfg.scoring.receptionPoints;
    var base = rec >= 1 ? 'full PPR' : rec >= 0.5 ? 'half-PPR' : rec > 0 ? rec + ' PPR' : 'standard';
    if (cfg.scoring.passingTD !== 4) base += ', ' + cfg.scoring.passingTD + '-point passing TDs';
    if (cfg.scoring.rbReceptionPoints !== rec) base += ', ' + cfg.scoring.rbReceptionPoints + ' per RB catch';
    return base;
  }
  // "+12% to +18%" / "-4%" out of an editorial effect line. Returns [lo, hi] as
  // fractions, or null when the line is qualitative — a story that never
  // quantified itself must not be handed a fabricated dollar figure.
  function pctRange(effect) {
    var m = String(effect || '').match(/([+-]?\d+(?:\.\d+)?)\s*%\s*(?:to|–|—|-)\s*([+-]?\d+(?:\.\d+)?)\s*%/);
    if (m) return [parseFloat(m[1]) / 100, parseFloat(m[2]) / 100];
    var s = String(effect || '').match(/([+-]\d+(?:\.\d+)?)\s*%/);
    return s ? [parseFloat(s[1]) / 100, parseFloat(s[1]) / 100] : null;
  }
  // The same sentence off the SITE's board — for a reader with no saved league,
  // and for one who saved a league but has never built a board. They are the
  // readers least able to translate a bare percentage themselves, so they get
  // the most of it: what the call is worth in dollars, what share of a manager's
  // budget that is, AND the draft-slot move — because there is no way to know
  // which of the two they came for, and guessing one would be worse than
  // printing both.
  //
  // Whose dollars those are is the whole question here. The board's own prices
  // are the desk's, and they stay that way — boardRatio() reads the same rows.
  // But a reader who HAS saved a league told us their budget and their league
  // size, and that is the entire content of an auction price: the sentence is
  // restated into their money by leagueScale() and names their league, exactly
  // as the lead's prices are. Quoting them $200 dollars because their board is
  // missing would be answering a question they already answered.
  //
  // What it does NOT claim is their scoring. Without a saved board there are no
  // stat lines to re-score, so the RANKS below are the site's, at the site's
  // scoring — which is why the copy names the league (teams and budget) and
  // never the rules. A reader with a board gets the real thing, in tailor().
  //
  // The percentage is the durable half: a dollar figure is only true at one
  // budget, but "4% of a budget" is true in every auction league there is. It is
  // computed from the raw share, not from the rounded dollars, so the two never
  // disagree at the rounding boundary.
  function tailorDefault(r, name, position) {
    var b = defaultBoard();
    if (!b.players.length) return '';
    var p = playerInText(name, position, b) || findPlayer(name, position, b);
    if (!p) return '';
    if ((p.v || 0) < 1) return '';
    // The reader's money when they have said what it is, the desk's when they
    // have not. k is 1 in the second case, so nothing here moves for them.
    var k = leagueScale();
    var teams = cfg ? cfg.teams : DEFAULT_TEAMS, budget = cfg ? cfg.budget : DEFAULT_BUDGET;
    var v = deskPrice(p.v);
    var lo = Math.min(r[0], r[1]), hi = Math.max(r[0], r[1]);
    var up = (lo + hi) / 2 > 0;
    var d1 = Math.max(1, Math.round(Math.abs(lo) * v)), d2 = Math.max(1, Math.round(Math.abs(hi) * v));
    if (d2 < d1) { var t = d1; d1 = d2; d2 = t; }
    var rng = d1 === d2 ? ('$' + d2) : ('$' + d1 + '\u2013$' + d2);

    // Share of ONE manager's budget, which is what a reader spends. Sub-1%
    // rounds to "under 1%" rather than to a bare 0, which would read as "no
    // effect" when the dollars beside it plainly say otherwise.
    var q1 = Math.abs(lo) * v / budget * 100, q2 = Math.abs(hi) * v / budget * 100;
    var qa = Math.round(Math.min(q1, q2)), qb = Math.round(Math.max(q1, q2));
    qa = Math.max(1, qa);
    var pct = qb < 1 ? 'under 1% of a budget'
            : qa >= qb ? qb + '% of a budget'
            : qa + '\u2013' + qb + '% of a budget';

    var m1 = slotMove(p, lo, b), m2 = slotMove(p, hi, b);
    var sa = Math.min(m1.slots, m2.slots), sb = Math.max(m1.slots, m2.slots);
    var far = m2.slots >= m1.slots ? m2.target : m1.target;
    var slots = slotPhrase(p, far, sa, sb, teams, budget, 'draft slot', k).text ||
      'less than one draft slot';
    var where = cfg ? label('auction') : 'a ' + DEFAULT_TEAMS + '-team, $' + DEFAULT_BUDGET + ' league';
    return p.n + ' prices at $' + v + ' in ' + where + ' \u2014 ' +
      (up ? 'worth about ' : 'trim about ') + rng + ', ' + pct + ', or ' + slots + '.';
  }

  // The whole point of the file, in one sentence of copy: what this call is
  // worth on the reader's own sheet, in their dollars or their draft slots.
  // formatOverride lets a page that offers a format switcher (my-insights, and
  // the front page's Position Intel) ask for the same call read as an auction, a
  // snake draft or best ball without touching the reader's saved league.
  function tailor(effect, name, position, formatOverride) {
    var r = pctRange(effect);
    if (!r) return '';
    if (!cfg || !snap) return tailorDefault(r, name, position);
    var fmt = formatOverride || cfg.format;
    // Whole-name containment first: callers pass free text (a headline as often
    // as a name field), and findPlayer's last-name fallback would happily read
    // "...is a reputation trap" as some player called Trap. playerInText only
    // ever matches a full name, so it is the safe reading of a sentence.
    var p = playerInText(name, position) || findPlayer(name, position);
    if (!p) return '';
    var lo = Math.min(r[0], r[1]), hi = Math.max(r[0], r[1]);
    var up = (lo + hi) / 2 > 0;
    if (fmt === 'auction') {
      var v = p.v || 0;
      if (v < 1) return '';
      var d1 = Math.max(1, Math.round(Math.abs(lo) * v)), d2 = Math.max(1, Math.round(Math.abs(hi) * v));
      if (d2 < d1) { var t = d1; d1 = d2; d2 = t; }
      var rng = d1 === d2 ? ('$' + d2) : ('$' + d1 + '–$' + d2);
      return p.n + ' is $' + v + ' on your sheet — ' +
        (up ? 'worth about ' + rng + ' more in ' + label(fmt) + '.' : 'trim about ' + rng + ' off in ' + label(fmt) + '.');
    }
    var m1 = slotMove(p, lo), m2 = slotMove(p, hi);
    var a = Math.min(m1.slots, m2.slots), b = Math.max(m1.slots, m2.slots);
    var far = m2.slots >= m1.slots ? m2.target : m1.target;
    var phrase = slotPhrase(p, far, a, b, cfg.teams, cfg.budget, 'slot');
    if (!phrase.text) return 'In ' + label(fmt) + ' the shift is less than one draft slot — treat it as a hold.';
    if (phrase.endgame) return 'In ' + label(fmt) + ' that is ' + phrase.text + ' for ' + p.n + '.';
    return 'Move ' + p.n + (up ? ' up ' : ' down ') + phrase.text + ' in ' + label(fmt) + '.';
  }

  // Which of the two lines tailor() just handed back, so a page can label it
  // truthfully. "Your league" over the desk's own dollars would be the one lie
  // this whole file exists to avoid — but a reader with a saved league is no
  // longer shown those: with or without a board of their own, the dollars in the
  // line are at their budget and the copy names their league. Without a league
  // there is nothing to call theirs, and the label says so.
  function tailorLabel() { return cfg ? 'Your league' : 'Default league'; }


  // ── the desk's dollars, in the reader's league ────────────────────────────
  // The generated lead (front.html, /lead) is written by a scheduled run at ONE
  // league: 12 teams, $200, the site's own default scoring. It quotes real
  // dollars in its headline and dek — "bid $32, not the sheet's $26" — and every
  // one of them is wrong for a reader who plays $300, or 10 teams, or half PPR.
  // The story cannot know who is reading it. This does.
  //
  // Two different corrections, and the difference matters:
  //   * A dollar attached to a NAMED PLAYER is re-anchored on that player's own
  //     price on the reader's board. That board was priced at their scoring, so
  //     this carries scoring, budget and league size at once — a full-PPR back
  //     and a standard-scoring back are not the same player, and no amount of
  //     budget scaling would say so.
  //   * A dollar attached to nobody (a pool, a tier, a gap) is scaled by the
  //     money in the room, (teams x budget), which is what every price on an
  //     auction board scales by.
  // Nothing is invented: with no saved league this returns null and the copy
  // ships exactly as the desk wrote it, labelled as the desk's own league.
  function boardRatio(name) {
    var site = defaultBoard();
    var sp = findPlayer(name, null, site);
    var mp = mine ? findPlayer(name, null, mine) : null;
    if (!sp || !mp) return 0;
    var a = sp.v || 0, b = mp.v || 0;
    if (a < 1 || b < 1) return 0;
    return b / a;
  }
  // The money in the room, relative to the room the desk writes for.
  function leagueScale() {
    return cfg ? (cfg.teams * cfg.budget) / (DEFAULT_TEAMS * DEFAULT_BUDGET) : 1;
  }
  // One price off the SITE's board, in the reader's money — the going rate that
  // board quotes, at the budget they actually spend. The board itself is left at
  // the desk's prices because boardRatio() reads it; this is the one place the
  // conversion lives, so a tile and a sentence quoting the same row cannot
  // disagree. Unchanged for a reader with no league, who is quoted the desk's.
  function deskPrice(v) {
    var n = num(v, 0);
    if (n < 1) return 0;
    return Math.max(MIN_BID, Math.round(n * leagueScale()));
  }
  function reEscape(s) { return String(s).replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }
  // Every place a story's named players are mentioned, with the ratio each one's
  // dollars move by. Surnames count as mentions — a dek names a player once in
  // full and then calls him "Henry" — but only when exactly one player in the
  // story carries that surname, because "Williams" against two Williamses would
  // price one of them off the other's board slot.
  // Names the copy uses that the story never listed. `players` carries at most
  // the four the story commits to, and a dek routinely prices a fifth in
  // passing ("...Garrett Wilson at $26 and DeVonta Smith at $26"). Left
  // undiscovered, that fifth player's dollars get attributed to the name before
  // him, which prices one player off another's board slot. Cheap to avoid: pull
  // the capitalised two- and three-word runs out of the copy and keep the ones
  // the reader's own board can name.
  function scanNames(text) {
    var re = /\b[A-Z][A-Za-z'\u2019.\-]+(?:\s+[A-Z][A-Za-z'\u2019.\-]+){1,2}/g;
    var out = [], seen = {}, m;
    while ((m = re.exec(String(text)))) {
      var words = m[0].split(/\s+/);
      for (var take = words.length; take >= 2; take--) {
        var cand = words.slice(0, take).join(' ');
        if (seen[cand]) break;
        if (mine && mine.byName[normName(cand)]) { seen[cand] = 1; out.push(cand); break; }
      }
    }
    return out;
  }
  function mentions(text, names) {
    var hay = String(text).toLowerCase(), out = [], surnames = {};
    var all = (names || []).slice();
    scanNames(text).forEach(function (n) {
      var dup = all.some(function (x) { return normName(x) === normName(n); });
      if (!dup) all.push(n);
    });
    names = all;
    (names || []).forEach(function (n) {
      var k = lastNameKey(n);
      if (k) surnames[k] = (surnames[k] || 0) + 1;
    });
    (names || []).forEach(function (n) {
      var r = boardRatio(n);
      if (!r) return;
      var full = String(n || '').trim();
      if (!full) return;
      var forms = [full];
      var k = lastNameKey(full);
      // Suffix off first: the last word of "Kenneth Walker III" is not his name.
      var bare = full.replace(/\s+(jr|sr|ii|iii|iv|v)\.?$/i, '').replace(/[.,]/g, ' ').trim().split(/\s+/);
      if (k && surnames[k] === 1 && bare.length > 1) forms.push(bare[bare.length - 1]);
      forms.forEach(function (f) {
        var re = new RegExp('\\b' + reEscape(f.toLowerCase()) + '\\b', 'g'), m;
        while ((m = re.exec(hay))) out.push({ at: m.index, ratio: r, who: full });
      });
    });
    return out.sort(function (a, b) { return a.at - b.at; });
  }
  // Where the sentence holding `at` begins, so a dollar figure is only ever
  // attributed to a player named in its own sentence. "Cap Drake London at $29,
  // Garrett Wilson at $26" has to give each figure to the player beside it, and
  // a name three sentences up is not that.
  function sentenceStart(text, at) {
    var cut = text.slice(0, at), m = cut.lastIndexOf('. ');
    var q = Math.max(cut.lastIndexOf('! '), cut.lastIndexOf('? '));
    return Math.max(0, Math.max(m, q) + 2);
  }
  function sentenceEnd(text, at) {
    var m = text.slice(at).search(/[.!?](\s|$)/);
    return m < 0 ? text.length : at + m;
  }
  // Restate one piece of the desk's copy — a headline, a dek, a whole article —
  // in the reader's money. Returns null when there is nothing to say: no saved
  // league, no dollars in the copy, or a reader whose league prices the story
  // the same way the desk already did.
  function repriceCopy(text, names) {
    if (!cfg || !text) return null;
    var src = String(text);
    if (!/\$\s?\d/.test(src)) return null;
    var anchors = mentions(src, names);
    var scale = leagueScale();
    var out = '', last = 0, changed = 0, anchored = 0;
    var re = /\$\s?(\d{1,4})\b/g, m;
    while ((m = re.exec(src))) {
      var n = parseInt(m[1], 10);
      var ratio = 0;
      if (anchors.length) {
        var lo = sentenceStart(src, m.index), hi = sentenceEnd(src, m.index), i;
        // The player named before the figure owns it; a figure that opens its
        // own sentence ("$32 is the bid on Flowers") falls forward to the next
        // name in the same sentence.
        for (i = anchors.length - 1; i >= 0; i--) {
          if (anchors[i].at < m.index && anchors[i].at >= lo) { ratio = anchors[i].ratio; break; }
        }
        if (!ratio) {
          for (i = 0; i < anchors.length; i++) {
            if (anchors[i].at > m.index && anchors[i].at <= hi) { ratio = anchors[i].ratio; break; }
          }
        }
        if (ratio) anchored++;
      }
      if (!ratio) ratio = scale;
      var v = Math.max(MIN_BID, Math.round(n * ratio));
      out += src.slice(last, m.index) + '$' + v;
      last = m.index + m[0].length;
      if (v !== n) changed++;
    }
    out += src.slice(last);
    if (!changed) return null;
    return { text: out, changed: changed, anchored: anchored, source: src };
  }
  // What league the dollars a reader is looking at belong to, said out loud.
  // The generated lead quotes prices with no percentage in sight, so tailor()'s
  // machinery has nothing to translate; what a reader needs instead is to know
  // whose league the number is for — which is the complaint that started this:
  // the front page was quoting $26 to a reader whose own sheet says $39.
  //
  // A reader who HAS saved a league is only ever told their own numbers. The
  // note used to append "the desk writes at 12 teams, $200, full PPR", and that
  // second league is what made the card unreadable: a reader on a $120 budget
  // was handed one set of prices and, in the same breath, a budget those prices
  // are not in, with nothing on screen priced at it. The desk's league is the
  // machinery, not the reading — so it is named only to the reader who is
  // actually being shown the desk's dollars, which is the reader with no league.
  //
  // `restated` is whether repriceCopy() actually moved the numbers. It only
  // chooses the verb: "restated" is a claim that something happened, and over
  // untouched figures it would be a lie in the other direction.
  function pricingNote(restated) {
    if (!cfg) {
      return 'These are ' + DEFAULT_TEAMS + '-team, $' + DEFAULT_BUDGET
        + ' full-PPR dollars. Set up your league and every price here is restated in your money.';
    }
    return (restated ? 'Restated for ' : 'Priced for ')
      + label('auction') + (snap ? ', ' + scoringLabel() : '') + '.';
  }

  // One stylesheet for the "Your league:" line, injected rather than copied into
  // forty pages' <style> blocks. It has to sit on the light front page and the
  // dark drop pages alike, so it borrows the reader's text colour and paints
  // only a translucent teal wash and rule — no palette assumptions beyond the
  // --teal token every page already defines, and a literal fallback if it does not.
  var STYLE_ID = 'it-league-css';
  function ensureStyle() {
    var doc = root.document;
    if (!doc || !doc.head || doc.getElementById(STYLE_ID)) return;
    var el = doc.createElement('style');
    el.id = STYLE_ID;
    el.textContent = '.it-yours{margin:6px 0 0;padding:6px 10px;font-size:12.5px;font-style:normal;' +
      'line-height:1.45;border-left:3px solid var(--teal,#2dd4a3);border-radius:0 4px 4px 0;' +
      'background:rgba(45,212,163,0.09)}' +
      '.it-dollars{color:var(--teal,#2dd4a3);font-weight:700;white-space:nowrap}';
    doc.head.appendChild(el);
  }

  // ── declarative rewrites, for pages that only need a number swapped ───────
  // A guide that says "in a $200, 12-team league" marks the figures up as
  // data-it-money / data-it-teams and this restates them in the reader's league.
  // Untouched when there is no league — the printed default is still true.
  // `scope` narrows WHAT is rewritten (a freshly rendered subtree, say); the
  // document is still what creates nodes, because an element is not a factory.
  function applyMarkup(scope) {
    if (!cfg) return;
    ensureStyle();
    var doc = root.document;
    var where = scope || doc;
    if (!doc || !where || !where.querySelectorAll) return;
    Array.prototype.forEach.call(where.querySelectorAll('[data-it-money]'), function (el) {
      var v = money(el.getAttribute('data-it-money'));
      if (v > 0) el.textContent = '$' + v;
    });
    Array.prototype.forEach.call(where.querySelectorAll('[data-it-teams]'), function (el) {
      el.textContent = String(cfg.teams);
    });
    Array.prototype.forEach.call(where.querySelectorAll('[data-it-league]'), function (el) {
      el.textContent = label();
    });
    // Allocation copy is written in percentages because a percentage is true in
    // every league. What it BUYS is not: 38% is $76 at $200 and $114 at $300.
    // data-it-pct="38-42" prints the reader's own band beside the percentage.
    Array.prototype.forEach.call(where.querySelectorAll('[data-it-pct]'), function (el) {
      if (el.getAttribute('data-it-filled')) return;
      var band = String(el.getAttribute('data-it-pct') || '').split('-');
      var lo = num(band[0], NaN), hi = num(band.length > 1 ? band[1] : band[0], NaN);
      if (!isFinite(lo) || !isFinite(hi)) return;
      var d1 = Math.round(cfg.budget * Math.min(lo, hi) / 100);
      var d2 = Math.round(cfg.budget * Math.max(lo, hi) / 100);
      var span = doc.createElement('span');
      span.className = 'it-dollars';
      span.textContent = ' (' + (d1 === d2 ? '$' + d2 : '$' + d1 + '\u2013$' + d2) + ')';
      el.parentNode.insertBefore(span, el.nextSibling);
      el.setAttribute('data-it-filled', '1');
    });
  }

  // Insight drop pages carry their calls as <p class="statline">Projected
  // effect: ...</p> under the call's <h2>. Any of them that quantified itself
  // gets the reader's own translation appended, once, on load.
  function tailorStatlines(scope) {
    var doc = root.document;
    var where = scope || doc;
    if (!doc || !where || !where.querySelectorAll) return 0;
    ensureStyle();
    var n = 0;
    Array.prototype.forEach.call(where.querySelectorAll('p.statline'), function (el) {
      if (el.getAttribute('data-it-tailored')) return;
      var call = el.closest ? el.closest('.call') : null;
      var host = call || el.parentNode;
      var h = host && host.querySelector ? host.querySelector('h2') : null;
      var posEl = call && call.querySelector ? call.querySelector('.cpos') : null;
      var pos = posEl ? (posEl.textContent || '').trim() : '';
      // The player can be in the headline (the insight drops name him there) or
      // in a "Who it moves" line (the coaching column's headlines name the
      // COACH, and the player only appears underneath). Search both, headline
      // first, so a call is never left untranslated because of where its
      // subject happens to sit.
      var whoEl = host && host.querySelector ? host.querySelector('p.who') : null;
      var subject = ((h ? h.textContent : '') + ' \u00b7 ' + (whoEl ? whoEl.textContent : '')).trim();
      var line = tailor(el.textContent, subject, pos, readingFormat());
      if (!line) return;
      var d = doc.createElement('p');
      d.className = 'it-yours';
      d.innerHTML = '<b>' + tailorLabel() + ':</b> ' + line.replace(/[&<>]/g, function (c) {
        return c === '&' ? '&amp;' : c === '<' ? '&lt;' : '&gt;';
      });
      el.parentNode.insertBefore(d, el.nextSibling);
      el.setAttribute('data-it-tailored', '1');
      n++;
    });
    return n;
  }

  root.ITLeague = {
    has: !!cfg,
    hasBoard: !!snap,
    custom: custom,
    customScoring: customScoring,
    customLeague: customLeague,
    config: cfg,
    defaults: { teams: DEFAULT_TEAMS, budget: DEFAULT_BUDGET, scoring: SCORING_DEFAULTS, curve: CURVE, curveBudget: CURVE_BUDGET },
    score: score,
    price: price,
    money: money,
    rankOf: rankOf,
    findPlayer: findPlayer,
    playerInText: playerInText,
    slotsMoved: slotsMoved,
    pctRange: pctRange,
    tailor: tailor,
    tailorLabel: tailorLabel,
    repriceCopy: repriceCopy,
    pricingNote: pricingNote,
    leagueScale: leagueScale,
    deskPrice: deskPrice,
    defaultBoard: function () { return defaultBoard().players; },
    readingFormat: readingFormat,
    setReadingFormat: setReadingFormat,
    formatFromLeague: formatFromLeague,
    edition: edition,
    setEdition: setEdition,
    editionFromLeague: editionFromLeague,
    label: label,
    scoringLabel: scoringLabel,
    ensureStyle: ensureStyle,
    applyMarkup: applyMarkup,
    tailorStatlines: tailorStatlines
  };

  // Pages opt in by including this file; the two auto-passes are safe no-ops on
  // a page with neither the markup nor a statline.
  function boot() { if (cfg) ensureStyle(); applyMarkup(); tailorStatlines(); }
  if (root.document) {
    // Paint the rule as early as the document allows: a page that renders its
    // own "Your league" lines from an inline script runs before DOMContentLoaded,
    // and an unstyled flash is a worse first impression than a slow one.
    if (cfg) ensureStyle();
    if (root.document.readyState === 'loading') root.document.addEventListener('DOMContentLoaded', boot);
    else boot();
  }
})(typeof window !== 'undefined' ? window : this);
