import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html = fs.readFileSync(new URL('../my-league.html', import.meta.url), 'utf8');
for (const m of html.matchAll(/<script(?: type="module")?>([\s\S]*?)<\/script>/g)) new Function(m[1]);
const start = html.indexOf('  function flow(k) {'), end = html.indexOf('  function discovered(k, j)', start);
assert(start > 0 && end > start);
const elements = new Map(), calls = [], notes = [], panels = [];
function $(id) {
  if (!elements.has(id)) elements.set(id, { value: '', innerHTML: '', addEventListener(type, fn) { this[type] = fn; } });
  return elements.get(id);
}
let reply = { ok: true, needsTeam: true, league: { id: 'test-id', name: 'Test League' } };
const context = vm.createContext({ $, st: { providers: { cbs: { enabled: true } } }, esc: String, note: (...a) => notes.push(a), reload: async () => {}, panel: (...a) => panels.push(a), ITSync: { api: async (url, req) => { calls.push({ url, req }); return reply; } } });
vm.runInContext(html.slice(start, end), context);
vm.runInContext("flow('cbs')", context);
assert.match($('lsFlow').innerHTML, /type="password"/);
assert.match($('lsFlow').innerHTML, /autocomplete="off"/);
await $('lsCbsConnect').click();
assert.equal(calls.length, 0);
$('lsCbsId').value = 'fixture'; $('lsCbsToken').value = 'test-secret';
$('lsCbsConnect').click();
assert.equal($('lsCbsToken').value, '');
await new Promise(resolve => setImmediate(resolve));
assert.equal(calls[0].url, '/api/leagues/connect');
assert.equal(calls[0].req.method, 'POST');
assert.equal(calls[0].req.body.accessToken, 'test-secret');
assert.deepEqual(panels[0], ['test-id', 'teams']);
assert.equal($('lsConnect').hidden, true);
reply = { ok: false, detail: 'CBS access expired' };
vm.runInContext("flow('cbs')", context);
$('lsCbsId').value = 'fixture'; $('lsCbsToken').value = 'new-secret';
$('lsCbsConnect').click();
await new Promise(resolve => setImmediate(resolve));
assert.equal($('lsCbsConnect').disabled, false);
assert.equal($('lsCbsToken').value, '');
assert.equal(notes.at(-1)[0], 'CBS access expired');
context.st.providers.cbs.enabled = false;
context.st.providers.cbs.reason = 'CBS is off';
vm.runInContext("flow('cbs')", context);
assert.equal($('lsFlow').innerHTML.includes('lsCbsToken'), false);
assert(!/localStorage|sessionStorage/.test(html.slice(start, end)));
console.log('CBS form: validation, masked input, POST, clearing, team selection, retry and disabled state passed.');
