import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html = fs.readFileSync(new URL('../my-league.html', import.meta.url), 'utf8');
const front = fs.readFileSync(new URL('../front.html', import.meta.url), 'utf8');
const worker = fs.readFileSync(new URL('../_worker.js', import.meta.url), 'utf8');
assert.match(front, /id="navSync" href="\/my-league">Sync My League<\/a>/);
assert.doesNotMatch(front.match(/<nav class="mast-nav">[\s\S]*?<\/nav>/)[0], /Save My League|Auction Manager/);
assert.match(html, /<b>League sync is free\.<\/b>/);
assert.match(html, /returnTo: '\/my-league'/);
assert.doesNotMatch(html, /League sync is part of the paid bundle/);
const authRequest = worker.slice(worker.indexOf("if (url.pathname === '/api/auth/request'"), worker.indexOf("if (url.pathname === '/api/auth/verify'"));
assert.doesNotMatch(authRequest, /await isEntitled/);
assert.match(authRequest, /r: returnTo/);
for (const m of html.matchAll(/<script(?: type="module")?>([\s\S]*?)<\/script>/g)) new Function(m[1]);
const start = html.indexOf('  function flow(k) {'), end = html.indexOf('  function discovered(k, j)', start);
assert(start > 0 && end > start);
const elements = new Map(), calls = [], notes = [], panels = [];
function $(id) {
  if (!elements.has(id)) elements.set(id, { value: '', innerHTML: '', textContent: '', style: {}, addEventListener(type, fn) { this[type] = fn; } });
  return elements.get(id);
}
let reply = { ok: true, needsTeam: true, league: { id: 'test-id', name: 'Test League' } };
let loaded = { providers: { cbs: { enabled: true } }, leagues: [{ id: 'test-id' }] };
const context = vm.createContext({ $, st: { providers: { cbs: { enabled: true } } }, esc: String, note: (...a) => notes.push(a), render: () => {}, panel: (...a) => panels.push(a), ITSync: { invalidate() {}, load: async () => loaded, api: async (url, req) => { calls.push({ url, req }); return reply; } } });
vm.runInContext(html.slice(start, end), context);
vm.runInContext("flow('cbs')", context);
assert.match($('lsFlow').innerHTML, /type="password"/);
assert.match($('lsFlow').innerHTML, /autocomplete="off"/);
assert.match($('lsFlow').innerHTML, /does not use your CBS email or password/);
assert.match($('lsFlow').innerHTML, /I do not have an API token/);
await $('lsCbsConnect').click();
assert.equal(calls.length, 0);
assert.match($('lsCbsMsg').textContent, /Enter the CBS football league address/);
$('lsCbsId').value = 'member@example.com'; $('lsCbsToken').value = 'not-a-token';
await $('lsCbsConnect').click();
assert.equal(calls.length, 0);
assert.match($('lsCbsMsg').textContent, /not a CBS football league address/);
$('lsCbsId').value = 'fixture'; $('lsCbsToken').value = 'test-secret';
$('lsCbsConnect').click();
assert.equal($('lsCbsToken').value, 'test-secret');
await new Promise(resolve => setImmediate(resolve));
assert.equal(calls[0].url, '/api/leagues/connect');
assert.equal(calls[0].req.method, 'POST');
assert.equal(calls[0].req.body.accessToken, 'test-secret');
assert.deepEqual(panels[0], ['test-id', 'teams']);
assert.equal($('lsConnect').hidden, true);
assert.equal($('lsCbsToken').value, '');
reply = { ok: false, detail: 'CBS access expired' };
vm.runInContext("flow('cbs')", context);
$('lsCbsId').value = 'fixture'; $('lsCbsToken').value = 'new-secret';
$('lsCbsConnect').click();
await new Promise(resolve => setImmediate(resolve));
assert.equal($('lsCbsConnect').disabled, false);
assert.equal($('lsCbsToken').value, 'new-secret');
assert.equal($('lsCbsMsg').textContent, 'CBS access expired');
reply = { ok: true, needsTeam: true, league: { id: 'test-id', name: 'Test League' } };
loaded = { error: true, leagues: [] };
$('lsConnect').hidden = false;
$('lsCbsConnect').click();
await new Promise(resolve => setImmediate(resolve));
assert.equal($('lsConnect').hidden, false);
assert.match($('lsCbsMsg').textContent, /league was synced.*could not refresh/);
context.ITSync.api = async () => { throw new Error('offline'); };
vm.runInContext("flow('cbs')", context);
$('lsCbsId').value = 'fixture'; $('lsCbsToken').value = 'retry-secret';
$('lsCbsConnect').click();
await new Promise(resolve => setImmediate(resolve));
assert.equal($('lsCbsConnect').disabled, false);
assert.equal($('lsCbsToken').value, 'retry-secret');
assert.match($('lsCbsMsg').textContent, /could not reach the sync service/);
context.st.providers.cbs.enabled = false;
context.st.providers.cbs.reason = 'CBS is off';
vm.runInContext("flow('cbs')", context);
assert.equal($('lsFlow').innerHTML.includes('lsCbsToken'), false);
assert(!/localStorage|sessionStorage/.test(html.slice(start, end)));
console.log('CBS form: credential warning, league validation, visible status, POST, success clearing, team selection and retry passed.');
